package com.example.btkeyboard.model

enum class ErrorCode {
    BLUETOOTH_UNAVAILABLE,
    BLUETOOTH_DISABLED,
    HID_UNSUPPORTED,
    PERMISSION_DENIED,
    REPAIR_REQUIRED,
    PROFILE_UNAVAILABLE,
    REGISTRATION_FAILED,
    CONNECTION_FAILED,
    DEVICE_NOT_BONDED,
    SEND_FAILED,
    DISCOVERY_FAILED,
    UNKNOWN,
}
